name: RBMM214
channels:
  - pytorch
  - nvidia
  - nvidia/label/cuda-11.8.0
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotli-python=1.0.9=py38h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - certifi=2024.8.30=py38h06a4308_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - cuda-cccl=11.8.89=0
  - cuda-command-line-tools=11.8.0=0
  - cuda-compiler=11.8.0=0
  - cuda-cudart=11.8.89=0
  - cuda-cudart-dev=11.8.89=0
  - cuda-cuobjdump=11.8.86=0
  - cuda-cupti=11.8.87=0
  - cuda-cuxxfilt=11.8.86=0
  - cuda-documentation=11.8.86=0
  - cuda-driver-dev=11.8.89=0
  - cuda-gdb=11.8.86=0
  - cuda-libraries=11.8.0=0
  - cuda-libraries-dev=11.8.0=0
  - cuda-memcheck=11.8.86=0
  - cuda-nsight=11.8.86=0
  - cuda-nsight-compute=11.8.0=0
  - cuda-nvcc=11.8.89=0
  - cuda-nvdisasm=11.8.86=0
  - cuda-nvml-dev=11.8.86=0
  - cuda-nvprof=11.8.87=0
  - cuda-nvprune=11.8.86=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvrtc-dev=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-nvvp=11.8.87=0
  - cuda-profiler-api=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cuda-sanitizer-api=11.8.86=0
  - cuda-toolkit=11.8.0=0
  - cuda-tools=11.8.0=0
  - cuda-version=12.6=3
  - cuda-visual-tools=11.8.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py38h06a4308_0
  - freetype=2.12.1=h4a9f257_0
  - gds-tools=1.4.0.31=0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=3.7=py38h06a4308_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jinja2=3.1.4=py38h06a4308_0
  - jpeg=9e=h5eee18b_3
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=3.0=h295c915_0
  - libcublas=11.11.3.6=0
  - libcublas-dev=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufft-dev=10.9.0.58=0
  - libcufile=1.11.1.6=0
  - libcufile-dev=1.4.0.31=0
  - libcurand=10.3.7.68=0
  - libcurand-dev=10.3.0.86=0
  - libcusolver=11.4.1.48=0
  - libcusolver-dev=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libcusparse-dev=11.7.5.86=0
  - libdeflate=1.17=h5eee18b_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - libnpp=11.8.0.86=0
  - libnpp-dev=11.8.0.86=0
  - libnvjpeg=11.9.0.86=0
  - libnvjpeg-dev=11.9.0.86=0
  - libpng=1.6.39=h5eee18b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.5.1=h6a678d5_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp-base=1.3.2=h5eee18b_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py38h5eee18b_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py38h5eee18b_1
  - mkl_fft=1.3.8=py38h5eee18b_0
  - mkl_random=1.2.4=py38hdb19cb5_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.3.0=py38h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.1=py38h06a4308_0
  - nsight-compute=2022.3.0.22=0
  - numpy=1.24.3=py38hf6e8229_1
  - numpy-base=1.24.3=py38h060ed82_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openssl=3.0.15=h5eee18b_0
  - pillow=10.4.0=py38h5eee18b_0
  - pip=24.2=py38h06a4308_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - pytorch=2.4.0=py3.8_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py38h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py38h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - sympy=1.13.2=py38h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tk=8.6.14=h39e8969_0
  - torchaudio=2.4.0=py38_cu118
  - torchtriton=3.0.0=py38
  - torchvision=0.19.0=py38_cu118
  - typing_extensions=4.11.0=py38h06a4308_0
  - urllib3=2.2.2=py38h06a4308_0
  - wheel=0.44.0=py38h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.5=hc292b87_2
  - pip:
    - absl-py==2.1.0
    - addict==2.4.0
    - antlr4-python3-runtime==4.9.3
    - asciitree==0.3.3
    - asttokens==2.4.1
    - attrs==24.2.0
    - backcall==0.2.0
    - beautifulsoup4==4.12.3
    - bleach==6.1.0
    - blinker==1.8.2
    - braceexpand==0.1.7
    - cachetools==5.5.0
    - cffi==1.17.1
    - click==8.1.7
    - cloudpickle==3.0.0
    - comm==0.2.2
    - configargparse==1.7
    - contourpy==1.1.1
    - cycler==0.12.1
    - dash==2.18.1
    - dash-core-components==2.0.0
    - dash-html-components==2.0.0
    - dash-table==5.0.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - einops==0.8.0
    - einops-exts==0.0.4
    - executing==2.1.0
    - farama-notifications==0.0.4
    - fasteners==0.19
    - fastjsonschema==2.20.0
    - flask==3.0.3
    - fonttools==4.54.1
    - fsspec==2024.9.0
    - ftfy==6.2.3
    - fvcore==0.1.5.post20221221
    - gitdb==4.0.11
    - gitpython==3.1.43
    - google-auth==2.35.0
    - google-auth-oauthlib==1.0.0
    - grpcio==1.66.2
    - gym==0.26.2
    - gym-notices==0.0.8
    - gymnasium==0.29.1
    - h5py==3.11.0
    - huggingface-hub==0.25.1
    - hydra-core==1.3.2
    - importlib-metadata==8.5.0
    - importlib-resources==6.4.5
    - iopath==0.1.10
    - ipython==8.12.3
    - ipywidgets==8.1.5
    - itsdangerous==2.2.0
    - jedi==0.19.1
    - joblib==1.4.2
    - jsonschema==4.23.0
    - jsonschema-specifications==2023.12.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyterlab-pygments==0.3.0
    - jupyterlab-widgets==3.0.13
    - kiwisolver==1.4.7
    - markdown==3.7
    - markdown-it-py==3.0.0
    - matplotlib==3.7.5
    - matplotlib-inline==0.1.7
    - mdurl==0.1.2
    - mistune==3.0.2
    - multiscaledeformableattention==1.0
    - natsort==8.4.0
    - nbclient==0.10.0
    - nbconvert==7.16.4
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - numcodecs==0.12.1
    - numpy-quaternion==2023.0.4
    - oauthlib==3.2.2
    - omegaconf==2.3.0
    - open-clip-torch==2.26.1
    - open3d==0.18.0
    - opencv-python==4.10.0.84
    - packaging==24.1
    - pandas==2.0.3
    - pandocfilters==1.5.1
    - parso==0.8.4
    - pexpect==4.9.0
    - pickleshare==0.7.5
    - pipreqs==0.5.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==4.3.6
    - plotly==5.24.1
    - portalocker==2.10.1
    - prompt-toolkit==3.0.48
    - protobuf==5.28.2
    - psutil==6.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - pyasn1==0.6.1
    - pyasn1-modules==0.4.1
    - pybullet==3.2.6
    - pycls==0.1.1
    - pycparser==2.22
    - pygments==2.18.0
    - pyhash==0.9.3
    - pyparsing==3.1.4
    - pyquaternion==0.9.9
    - pyrep==4.1.0.3
    - python-dateutil==2.9.0.post0
    - pytorch3d==0.3.0
    - pytz==2024.2
    - pyzmq==26.2.0
    - referencing==0.35.1
    - regex==2024.9.11
    - requests-oauthlib==2.0.0
    - retrying==1.3.4
    - rich==13.8.1
    - rlbench==1.2.0
    - rpds-py==0.20.0
    - rsa==4.9
    - safetensors==0.4.5
    - scikit-learn==1.3.2
    - scipy==1.10.1
    - sentry-sdk==2.14.0
    - setproctitle==1.3.3
    - setuptools==57.5.0
    - simplejson==3.19.3
    - six==1.16.0
    - smmap==5.0.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - tabulate==0.9.0
    - tenacity==9.0.0
    - tensorboard==2.14.0
    - tensorboard-data-server==0.7.2
    - termcolor==2.4.0
    - threadpoolctl==3.5.0
    - timm==1.0.9
    - tinycss2==1.3.0
    - tokenizers==0.20.0
    - tornado==6.4.1
    - tqdm==4.66.5
    - traitlets==5.14.3
    - transformers==4.45.1
    - tzdata==2024.2
    - wandb==0.18.2
    - wcwidth==0.2.13
    - webdataset==0.2.100
    - webencodings==0.5.1
    - werkzeug==3.0.4
    - widgetsnbextension==4.0.13
    - yacs==0.1.8
    - yarg==0.1.9
    - zarr==2.16.1
    - zipp==3.20.2
prefix: /software/anaconda3/envs/RBMM214
